export const skillGroups = {
    "Design & Creativity": [
        { name: "Adobe After Effects", icon: "adobeaftereffects.png" },
        { name: "Adobe Animate", icon: "adobeanimate.png" },
        { name: "Adobe Audition", icon: "adobeaudition.png" },
        { name: "Adobe Bridge", icon: "adobebridge.png" },
        { name: "Adobe Creative Cloud", icon: "adobecreativecloud.png" },
        { name: "Adobe Dreamweaver", icon: "adobedreamweaver.png" },
        { name: "Adobe Fireworks", icon: "adobefireworks.png" },
        { name: "Adobe Flash", icon: "adobeflash.png" },
        { name: "Adobe FrameMaker", icon: "adobeframemaker.png" },
        { name: "Adobe Illustrator", icon: "adobeillustrator.png" },
        { name: "Adobe InDesign", icon: "adobeindesign.png" },
        { name: "Adobe Lightroom", icon: "adobelightroom.png" },
        { name: "Adobe Media Encoder", icon: "adobemediaencoder.png" },
        { name: "Adobe Photoshop", icon: "adobephotoshop.png" },
        { name: "Adobe Premiere Pro", icon: "adobepremierepro.png" },
        { name: "Adobe Substance Sampler", icon: "adobesubstancesampler.png" },
        { name: "Adobe XD", icon: "adobexd.png" },
        { name: "Affinity Publisher", icon: "affinitypublisher.png" },
        { name: "Autodesk Maya", icon: "autodeskmaya.png" },
        { name: "Camtasia", icon: "camtasia.png" },
        { name: "Canva", icon: "canva.png" },
        { name: "Cinema 4D", icon: "cinema4d.png" },
        { name: "CorelDRAW", icon: "coreldraw.png" },
        { name: "Figma", icon: "figma.png" },
        { name: "GIMP", icon: "gimp.png" },
        { name: "HitFilm Express", icon: "hitfilmexpress.png" },
        { name: "HitFilm Pro", icon: "hitfilmpro.png" },
        { name: "IbisPaint X", icon: "ibispaintx.png" },
        { name: "Inkscape", icon: "inkscape.png" },
        { name: "Sketch", icon: "sketch.png" }
    ],
    "Web Development": [
        { name: "AdonisJS", icon: "adonisjs.png" },
        { name: "AngularJS", icon: "angularjs.png" },
        { name: "Apache Tomcat", icon: "apachetomcat.png" },
        { name: "Bootstrap", icon: "bootstrap.png" },
        { name: "Bubblehouse", icon: "bubblehouse.png" },
        { name: "Django", icon: "django.png" },
        { name: "Express.js", icon: "expressjs.png" },
        { name: "Flask", icon: "flask.png" },
        { name: "GraphQL", icon: "graphql.png" },
        { name: "HTML", icon: "html.png" },
        { name: "JavaScript", icon: "javascript.png" },
        { name: "jQuery", icon: "jquery.png" },
        { name: "Laravel", icon: "laravel.png" },
        { name: "Next.js", icon: "next.js.png" },
        { name: "Nuxt.js", icon: "nuxtjs.png" },
        { name: "Node.js", icon: "nodejs.png" },
        { name: "npm", icon: "npm.png" },
        { name: "PHP", icon: "php.png" },
        { name: "React", icon: "react.png" },
        { name: "React Native", icon: "reactnative.png" },
        { name: "RecoilJS", icon: "recoiljs.png" },
        { name: "Redux", icon: "redux.png" },
        { name: "Ruby on Rails", icon: "rubyonrails.png" },
        { name: "Scratch", icon: "scratch.png" },
        { name: "Svelte", icon: "svelte.png" },
        { name: "Tailwind CSS", icon: "tailwindcss.png" },
        { name: "TypeScript", icon: "typescript.png" },
        { name: "Vite", icon: "vite.png" },
        { name: "Vue.js", icon: "vuejs.png" },
        { name: "Webpack", icon: "webpack.png" },
        { name: "WordPress", icon: "wordpress.png" }
    ],
    "Programming Languages": [
        { name: "Bash", icon: "bash.png" },
        { name: "C", icon: "c.png" },
        { name: "C++", icon: "c++.png" },
        { name: "C#", icon: "csharp.png" },
        { name: "Dart", icon: "dart.png" },
        { name: "Go", icon: "go.png" },
        { name: "Haskell", icon: "haskell.png" },
        { name: "Java", icon: "java.png" },
        { name: "Kotlin", icon: "kotlin.png" },
        { name: "Lua", icon: "lua.png" },
        { name: "MATLAB", icon: "matlab.png" },
        { name: "Perl", icon: "perl.png" },
        { name: "Python", icon: "python.png" },
        { name: "R", icon: "r.png" },
        { name: "Rust", icon: "rustprogramminglanguage.png" },
        { name: "Swift", icon: "swift.png" }
    ],
    "Database & ORM": [
        { name: "Doctrine", icon: "doctrine.png" },
        { name: "Elasticsearch", icon: "elasticsearch.png" },
        { name: "InfluxDB", icon: "influxdb.png" },
        { name: "MariaDB", icon: "mariadb.png" },
        { name: "Microsoft SQL Server", icon: "microsoftsqlserver.png" },
        { name: "MongoDB", icon: "mongodb.png" },
        { name: "MySQL", icon: "mysql.png" },
        { name: "Neo4j", icon: "neo4j.png" },
        { name: "Oracle", icon: "oraclelogo.png" },
        { name: "PostgreSQL", icon: "postgresql.png" },
        { name: "Prisma ORM", icon: "prismaorm.png" },
        { name: "Redis", icon: "redis.png" },
        { name: "SQLite", icon: "sqlite.png" }
    ],
    "Data Science & ML": [
        { name: "Colab", icon: "colab.png" },
        { name: "Hadoop Distributed File System", icon: "hadoopdistributedfilesystem.png" },
        { name: "Jupyter", icon: "jupyter.png" },
        { name: "Keras", icon: "keras.png" },
        { name: "Kibana", icon: "kibana.png" },
        { name: "Matplotlib", icon: "matplotlib.png" },
        { name: "NumPy", icon: "numpy.png" },
        { name: "OpenCV", icon: "opencv.png" },
        { name: "Pandas", icon: "pandas.png" },
        { name: "PyTorch", icon: "pytorch.png" },
        { name: "Scikit-learn", icon: "scikitlearn.png" },
        { name: "Seaborn", icon: "seaborn.png" },
        { name: "Tableau", icon: "tableausoftware.png" },
        { name: "TensorFlow", icon: "tensorflow.png" }
    ],
    "DevOps & Cloud": [
        { name: "Amazon Web Services", icon: "amazonwebservices.png" },
        { name: "Ansible", icon: "ansible.png" },
        { name: "Azure", icon: "azure.png" },
        { name: "Docker", icon: "docker.png" },
        { name: "Grafana", icon: "grafana.png" },
        { name: "Jenkins", icon: "jenkins.png" },
        { name: "Kubernetes", icon: "kubernetes.png" },
        { name: "Nginx", icon: "nginx.png" },
        { name: "OpenShift", icon: "openshift.png" },
        { name: "Prometheus", icon: "prometheus.png" },
        { name: "Terraform", icon: "terraform.png" },
        { name: "Vagrant", icon: "vagrant.png" },
        { name: "Apache Kafka", icon: "apachekafka.png" }
    ],
    "Mobile & Cross Platform": [
        { name: "Android Studio", icon: "androidstudio.png" },
        { name: "Flutter", icon: "flutter.png" },
        { name: "Xcode", icon: "xcode.png" }
    ],
    "Office & Productivity": [
        { name: "Microsoft Access", icon: "microsoftaccess.png" },
        { name: "Microsoft Excel", icon: "microsoftexcel.png" },
        { name: "Microsoft Exchange", icon: "microsoftexchange.png" },
        { name: "Microsoft Forms", icon: "microsoftforms.png" },
        { name: "Microsoft Lens", icon: "microsoftlens.png" },
        { name: "Microsoft Office", icon: "microsoftoffice.png" },
        { name: "Microsoft OneNote", icon: "microsoftonenote.png" },
        { name: "Microsoft Outlook", icon: "microsoftoutlook.png" },
        { name: "Microsoft PowerPoint", icon: "microsoftpowerpoint.png" },
        { name: "Microsoft Project", icon: "microsoftproject.png" },
        { name: "Microsoft Publisher", icon: "microsoftpublisher.png" },
        { name: "Microsoft Sway", icon: "microsoftsway.png" },
        { name: "Microsoft Word", icon: "microsoftword.png" }
    ],
    "Game Development": [
        { name: "Godot", icon: "godot.png" },
        { name: "Unity", icon: "unity.png" },
        { name: "Unreal Engine", icon: "unrealengine.png" }
    ],
    "Networking & Security": [
        { name: "Burp Suite", icon: "burpsuite.png" },
        { name: "Cisco Packet Tracer", icon: "ciscopackettracer.png" },
        { name: "Kali Linux", icon: "kalilinux.png" },
        { name: "Metasploit", icon: "metasploit.png" },
        { name: "Nmap", icon: "nmap.png" },
        { name: "Wireshark", icon: "wireshark.png" }
    ],
    "Version Control & CI/CD": [
        { name: "Git", icon: "git.png" },
        { name: "GitHub", icon: "github.png" },
        { name: "GitLab", icon: "gitlab.png" }
    ],
    "Operating Systems & Platforms": [
        { name: "Arch Linux", icon: "archlinux.png" },
        { name: "Raspberry Pi", icon: "raspberrypi.png" },
        { name: "Ubuntu Studio", icon: "ubuntustudio.png" }
    ],
    "IDEs & Editors": [
        { name: "Apache NetBeans", icon: "apachenetbeans.png" },
        { name: "Delphi IDE", icon: "delphiide.png" },
        { name: "Eclipse", icon: "eclipse.png" },
        { name: "JetBrains", icon: "jetbrains.png" },
        { name: "Visual Studio", icon: "visualstudio.png" },
        { name: "Visual Studio Code", icon: "visualstudiocode.png" }
    ],
    "Other Tools": [
        { name: "Autodesk Maya", icon: "autodeskmaya.png" },
        { name: "Bash", icon: "bash.png" },
        { name: "Caesium", icon: "caesium.png" },
        { name: "CMake", icon: "cmake.png" },
        { name: "Jira", icon: "jira.png" },
        { name: "LaTeX", icon: "latex.png" },
        { name: "Maven", icon: "maven.png" },
        { name: "Matrix", icon: "matrix.png" },
        { name: "Nvidia", icon: "nvidia.png" },
        { name: "Qt", icon: "qt.png" },
        { name: "Salesforce", icon: "salesforce.png" },
        { name: "Scratch", icon: "scratch.png" },
        { name: "Splunk", icon: "splunk.png" },
        { name: "Swagger", icon: "swagger.png" },
        { name: "Wolff Framework", icon: "wolffframework.png" }
    ]
};